ame: CI

# Controls when the action will run.
# Triggers the workflow on push or pull request events
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ 3.6, 3.7, 3.8 ]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install Dev Requirments
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt

      - name: Pull cromwell and mysql dockers
        run: |
          docker pull broadinstitute/cromwell
          docker pull mysql

      - name: Install Tox
        run: pip install tox

      - name: Run Tox lint commands
        # Run tox using the version of Python in `PATH`
        run: tox -e lint

      - name: Run Pytest through Tox
        # Run tox using the version of Python in `PATH`
        run: tox -e unit