# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
# Triggers the workflow on push or pull request events
on: [push, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: bshifaw/cromshell-unit-test:latest
    strategy:
      matrix:
        python: [ 3.6, 3.7, 3.8 ]


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install pip
        run: python -m pip install --upgrade pip

      - name: Install Tox
        run: pip install tox

      - name: Install Dev Requirments
        run: pip install -r dev-requirements.txt

      - name: Run Tox lint commands
        # Run tox using the version of Python in `PATH`
        run: tox -e lint

      - name: Run Pytest through Tox
        # Run tox using the version of Python in `PATH`
        run: tox -e unit
