# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
# Triggers the workflow on push or pull request events
on: [push, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ 3.6, 3.7, 3.8 ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install Tox
        run: pip install tox

      - name: Install Dev Requirments
        run: pip install -r dev-requirements.txt

      - name: Install downloaders
        run: sudo apt update -y && sudo apt upgrade -y && sudo apt install -y curl wget

      - name: Install Java
        run: sudo apt install -y --no-install-recommends default-jre

      # Use curl to get the JSON response for the latest release
      # Use grep to find the line containing file URL
      # Use cut and tr to extract the URL
      # Use wget to download it
      - name: Install Latest WomTool
        run: curl -s https://api.github.com/repos/broadinstitute/cromwell/releases/latest | grep "browser_download_url.*womtool" | cut -d '"' -f 4 | wget -qi -

      - name: list dr
        run: ls .

      - name: Create Alias for WomTool
        run: alias womtool="java -jar ${PWD}/womtool-*"

      - name: check alias
        run: type alias

      - name: list alias
        run: alias -p

      - name: Confirm Alias for WomTool
        run: womtool --help

      - name: Run Tox lint commands
        # Run tox using the version of Python in `PATH`
        run: tox -e lint

      - name: Run Pytest through Tox
        # Run tox using the version of Python in `PATH`
        run: tox -e unit
